2022-08-26 17:17:20.167 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-26 17:17:38.153 WARNING (MainThread) [homeassistant.components.generic.camera] Loading generic IP camera via configuration.yaml is deprecated, it will be automatically imported.  Once you have confirmed correct operation, please remove 'generic' (IP camera) section(s) from configuration.yaml
2022-08-26 17:17:38.177 WARNING (MainThread) [homeassistant.components.generic.camera] Loading generic IP camera via configuration.yaml is deprecated, it will be automatically imported.  Once you have confirmed correct operation, please remove 'generic' (IP camera) section(s) from configuration.yaml
2022-08-26 17:17:38.180 WARNING (MainThread) [homeassistant.components.generic.camera] Loading generic IP camera via configuration.yaml is deprecated, it will be automatically imported.  Once you have confirmed correct operation, please remove 'generic' (IP camera) section(s) from configuration.yaml
2022-08-26 17:26:02.352 WARNING (MainThread) [zeroconf] Error with socket 16 (('10.1.10.37', 5353))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1054, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2022-08-26 17:26:02.362 WARNING (MainThread) [zeroconf] Error with socket 17 (('fe80::4636:4252:b00b:417b', 5353, 0, 4))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1054, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2022-08-26 17:26:06.956 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/interface/wlan0/update - Activating connection failed, check connection settings.
2022-08-26 17:27:37.852 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/auth/token'. (Home Assistant/2022.8 (io.robbie.HomeAssistant; build:2022.387; iOS 15.6.1) Alamofire/5.4.4)
2022-08-26 17:28:33.251 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.8 (io.robbie.HomeAssistant; build:2022.387; iOS 15.6.1) Mobile/HomeAssistant, like Safari)
2022-08-26 17:29:27.928 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2022-08-26 17:32:36.965 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/auth/login_flow/d98415eb524be5e8b1110791d1b0a0e9'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1)
2022-08-26 17:32:46.573 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/auth/login_flow/d98415eb524be5e8b1110791d1b0a0e9'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1)
2022-08-26 17:33:00.644 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/auth/login_flow/d98415eb524be5e8b1110791d1b0a0e9'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1)
2022-08-26 17:33:17.154 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/auth/login_flow/ba0101cbe615bd22e17f2f348d67b322'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1)
2022-08-26 20:17:57.007 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Try again]
2022-08-26 21:12:18.278 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.8.0.3 (10.8.0.3). Requested URL: '/auth/login_flow/5f75873769f0f151f888817fb13df958'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-26 21:13:47.419 ERROR (MainThread) [homeassistant.components.zwave_js.config_flow] Failed to get Z-Wave JS add-on discovery info
2022-08-26 21:13:52.444 ERROR (MainThread) [homeassistant.components.zwave_js.config_flow] Failed to get Z-Wave JS add-on discovery info
2022-08-26 21:13:57.465 ERROR (MainThread) [homeassistant.components.zwave_js.config_flow] Failed to get Z-Wave JS add-on discovery info
2022-08-26 21:14:02.489 ERROR (MainThread) [homeassistant.components.zwave_js.config_flow] Failed to get Z-Wave JS add-on discovery info
2022-08-26 21:23:13.927 ERROR (MainThread) [homeassistant.components.hassio.http] Client timeout error on API request addons/ccab4aaf_frigate/documentation
2022-08-26 21:40:47.062 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
